# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    #increment Version
    increment_version_code
    commit_android_version_bump
    push_to_git_remote
    
    #build
    gradle(task: 'assembleRelease')
    
    #release_notes
    changelog_from_git_commits
    
    #upload
    upload_to_play_store(track: 'beta')
    
    #notify
    slack_notification(message: "Build has been uploaded",
        channel: "#general",
        username: "zezzitest",
        slack_hook: 'https://hooks.slack.com/services/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')
  end

  desc "Sends a Slack Notification to mobile/iOS room"
  private_lane :slack_notification do |options|
    color = options[:success] ? "good" : "warning"
    slack(
         message: options[:message],
         success: false,
         channel: options[:channel],
         username: options[:username],
         default_payloads: [],
         slack_url: options[:slack_hook],
         attachment_properties: {
             color: "danger",
             ts: Time.now.to_i
         }
     )
    end
end

#gradle(task: 'assembleDebug assembleAndroidTest')
